version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - '5435:5432'
    container_name: "database-postgres"
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  redis:
    image: redis
    command: redis-server --requirepass admin
    ports:
      - '6379:6379'
    volumes:
      - redis:/data


volumes:
  redis:
    driver: local